name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          git \
          unzip \
          openjdk-17-jdk \
          libssl-dev \
          libffi-dev \
          zlib1g-dev \
          libncurses-dev \
          autoconf \
          automake \
          libtool \
          pkg-config \
          autoconf-archive \
          libltdl-dev \
          wget
        
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip wheel
        pip install buildozer cython==0.29.33
        
    - name: Check disk space
      run: |
        df -h
        sudo rm -rf /usr/local/lib/android/sdk/ndk-bundle
        sudo apt-get clean
        
    - name: Install Android NDK manually
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        wget -q --show-progress --progress=bar:force:noscroll https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -t android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip -d ~/.buildozer/android/platform/
        rm android-ndk-r25b-linux.zip
        echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gamification-apk
        path: bin/*.apk
        if-no-files-found: error
