name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          git \
          unzip \
          openjdk-17-jdk \
          libssl-dev \
          libffi-dev \
          zlib1g-dev \
          libncurses-dev \
          autoconf \
          automake \
          libtool \
          pkg-config
        
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip wheel
        pip install buildozer cython==0.29.33
        
    - name: Prepare Buildozer environment
      run: |
        mkdir -p ~/.buildozer/android/platform
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
    - name: Setup NDK 25b
      run: |
        cd ~/.buildozer/android/platform
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        rm android-ndk-r25b-linux.zip
        echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
        
    - name: Patch libffi build
      run: |
        # Обновляем autoconf
        sudo apt-get install -y autoconf-archive
        
        # Клонируем и патчим libffi
        git clone https://github.com/libffi/libffi.git ~/libffi
        cd ~/libffi
        git checkout v3.4.6  # Используем стабильную версию
        autoreconf -fiv
        cd ..
        
    - name: Configure buildozer.spec
      run: |
        echo -e "\nandroid.ndk = 25b" >> buildozer.spec
        echo "android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b" >> buildozer.spec
        echo "p4a.local_recipes = $HOME/libffi" >> buildozer.spec
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gamification-apk
        path: bin/*.apk
        if-no-files-found: error
