name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          git \
          unzip \
          openjdk-17-jdk \
          libssl-dev \
          libffi-dev \
          zlib1g-dev \
          libncurses-dev
        
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip wheel
        pip install buildozer cython==0.29.33
        
    - name: Create Buildozer directories
      run: |
        mkdir -p ~/.buildozer/android/platform
        echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        
    - name: Download and install NDK 25b
      run: |
        cd ~/.buildozer/android/platform
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        rm android-ndk-r25b-linux.zip
        echo "ANDROIDNDK=~/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
        
    - name: Build APK
      run: |
        buildozer init
        sed -i 's/android.ndk = .*/android.ndk = 25b/' buildozer.spec
        sed -i 's/android.ndk_path = .*/android.ndk_path = ~\/.buildozer\/android\/platform\/android-ndk-r25b/' buildozer.spec
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gamification-apk
        path: bin/*.apk
        if-no-files-found: error
