name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          autoconf \
          automake \
          cmake \
          gettext \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libtinfo5 \
          build-essential \
          git \
          unzip \
          openjdk-17-jdk \
          libssl-dev \
          libffi-dev \
          python3-venv
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install buildozer cython==0.29.33 virtualenv
    
    - name: Build APK with Buildozer
      run: |
        buildozer init
        buildozer -v android debug
        ls -la bin/
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: gamification-apk
        path: bin/*.apk
        if-no-files-found: error
        retention-days: 5
