name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          autoconf \
          automake \
          cmake \
          gettext \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libtinfo5 \
          build-essential \
          git \
          unzip \
          openjdk-11-jdk
    
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install buildozer cython==0.29.33 virtualenv
    
    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
        ls -la bin/
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: gamification-apk
        path: bin/*.apk
