name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev python3-pip
        pip3 install --upgrade pip
        pip3 install buildozer cython
        
    - name: Install buildozer dependencies
      run: |
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        
    - name: Initialize buildozer
      run: |
        buildozer init
      continue-on-error: true
      
    - name: Build APK
      run: |
        buildozer android debug
      timeout-minutes: 30
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: statmaster-apk
        path: bin/*.apk
        if-no-files-found: warn
