name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          git \
          unzip \
          openjdk-17-jdk \
          libssl-dev \
          libffi-dev \
          zlib1g-dev \
          libncurses-dev \
          autoconf \
          automake \
          libtool \
          pkg-config \
          autoconf-archive \
          libltdl-dev \
          wget \
          curl
        
    - name: Clean disk space
      run: |
        df -h
        sudo rm -rf /usr/local/lib/android/sdk/ndk-bundle
        sudo apt-get clean
        sudo swapoff -a && sudo swapon -a
        
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip wheel
        pip install buildozer cython==0.29.33
        
    - name: Install Android NDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        wget --tries=3 https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        rm android-ndk-r25b-linux.zip
        echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
        
    - name: Install Android SDK and Tools
      run: |
        # Создаем правильную структуру директорий
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
        cd ~/.buildozer/android/platform/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools latest
        rm commandlinetools-linux-9477386_latest.zip
        
        # Добавляем в PATH
        echo "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_PATH
        
        # Принимаем лицензии
        yes | sdkmanager --licenses
        
        # Устанавливаем компоненты
        sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-33"
        
        # Проверяем установку
        ls -la $HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0/aidl
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gamification-apk
        path: bin/*.apk
        if-no-files-found: error
