name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build with Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        repository_root: .
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: statmaster-apk
        path: bin/*.apk
        if-no-files-found: warn
